# QUESTION 2

![](images/question_2_text.png)

In [1]:
# Import needed module
import numpy
import random

# For consistent results we seed
random.seed(6)

In [2]:
# First, we will generate all the computers in the network
num_computers : int = 20
computers : numpy.ndarray = numpy.zeros(num_computers)

# And we will say that the first computer is infected. It doesn't matter
# which computer we say is infected, as computers here are indistinguishable. 
# (All connected)
computers[0] = 1 # The infection begins!

In [3]:
# Now we will need to generate a "turn". To do that, we need to take into account
# the rules that have been given to us in the beggining of the sheet. Namely:
# (a) Each computer has a 0.1 chance to infect any other uninfected computer
# (b) Every day technician removed virus from any 5 computers (assume this happens second)

# First, we write some helped functions

# Probability function
def prob(probability : float = 0.1) -> bool:
    # @params probability: chance of yes or no
    # @return if infected or not
    return random.random() < probability

def num_infected() -> int:
    # @return Num infected computers
    return numpy.count_nonzero( computers == 1 )
computers

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [4]:

# Function (a)
def infect() -> None: # Since computers is global we don't need to pass it in
    # Processes infecting computers
    # @return None
    for inf in range(num_infected()): # For each infected computer
        for i in range(len(computers)):# Go through the array of computers
            if not computers[i]: # If 0 (not infected)
                if prob(0.1): # check if we infect
                    computers[i] = 1 # If yes, infect!
            
computers

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [5]:
# Function (b)
def IT(max_fix : int = 5) -> None:
    # Fixes total of max_fix computers
    # @return None
    computers_fixed : int = 0
    for i in range(len(computers)): # We go through all comps since order doesn't matter
        if computers[i] and computers_fixed <= max_fix: # is infected and we have fixes left
            computers[i] = 0 # Cure the infection
            computers_fixed+=1
computers

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
# Turn function
def process_turn() -> None:
    # Now we run the two functions we built
    infect()
    IT()
computers

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
infect()
IT()
computers

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])